name: Publish snap

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - charmed-bacula-server/**

jobs:
  build:
    name: Build charmed-bacula-server snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v41.1.0
    with:
      path-to-snap-project-directory: ./charmed_bacula_server

  release:
    name: Release charmed-bacula-server snap
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_snap.yaml@v41.1.0
    with:
      path-to-snap-project-directory: ./charmed_bacula_server
      channel: latest/edge
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      snap-store-token: ${{ secrets.SNAPSTORE_TOKEN }}
    permissions:
      contents: write  # Needed to create git tags
