name: Tests

on:
  pull_request:
  schedule:
  - cron: "0 15 * * SAT"

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      self-hosted-runner: true
      self-hosted-runner-label: "edge"
  integration-tests:
    strategy:
      fail-fast: false
      matrix:
        base:
          - "ubuntu@24.04"
          - "ubuntu@22.04"
    uses: 
      canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      juju-channel: "3/stable"
      provider: "lxd"
      extra-arguments: "--base=${{ matrix.base }}"
      tmate-debug: true
      tmate-timeout: 180
  snap-tests:
    name: Build charmed-bacula-server snap
    uses: 
      canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v36.0.1
    with:
      path-to-snap-project-directory: ./charmed_bacula_server
  allure-report:
    if: ${{ !cancelled() && github.event_name == 'schedule' }}
    needs:
    - integration-tests
    uses: canonical/operator-workflows/.github/workflows/allure_report.yaml@main
